url: http://envirology.github.io
remote_theme: jekyll/minima@49f6dce0727a2441f0b0c265b41b5efc7b042eb6
title: Envirology
show_excerpts: true
header_pages:
  - index.md
  # - news.md
  - about.html
repository: envirology/envirology.github.io
minima:
  social_links:
    twitter: ic_envirology
    github: envirology
